version: 2
jobs:
  build_and_test:
    working_directory: ~/sifrr-animate
    docker:
      - image: circleci/node:10-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "22:0a:b8:85:e7:5a:96:2a:90:5c:16:01:d6:1f:e8:b6"
      - restore_cache:
          keys:
            - sifrr-animate-v1-source-{{ .Branch }}-{{ .Revision }}
            - sifrr-animate-v1-source-{{ .Branch }}-
            - sifrr-animate-v1-source-
      - checkout
      - save_cache:
          key: sifrr-animate-v1-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - restore_cache:
          keys:
            - sifrr-animate-v1-yarn-{{ checksum "yarn.lock" }}
            - sifrr-animate-v1-yarn-
      - run:
          name: Yarn install
          command: yarn install
      - save_cache:
          key: sifrr-animate-v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Check chrome version
          command: google-chrome --version
      - run:
          name: Add git user email and name
          command: |
            git config --global user.email "aadityataparia@gmail.com"
            git config --global user.name "Aaditya Taparia"
      - run:
          name: Update dist files
          command: ./scripts/distribute
      - run:
          name: Run tests
          command: COVERAGE=true LCOV=true yarn test -j
      - run:
          name: New Release
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              ./scripts/publish
            fi
      - store_test_results:
          path: test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
