#!/usr/bin/env bash

set -ex

# ./scripts/checktag || exit 0
./scripts/changelog
git add misc/CHANGELOG.md
# (git commit -m "chore: update changelog" && git push) || echo 'Changelog up to date'
# ./scripts/release/tag
# npm publish --access=public
