#!/usr/bin/env bash

set -x

STATUS=0

if [[ $COVERAGE == 'true' ]]; then
  rm -rf ./.nyc_output
fi

yarn build
echo "Running test in `pwd`:"
node ./scripts/test/run.js "./" "$@"

NEW_STATUS=$?
[ $NEW_STATUS -eq 0 ] || STATUS=$NEW_STATUS

if [[ $LCOV == 'true' ]]; then
  cat ./coverage/lcov.info | yarn coveralls
fi

exit $STATUS # Exit with 1 if any test failed
